name: educaplay
description: "EducaPlay - Aplicativo educativo infantil para alfabetização e desenvolvimento cognitivo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado (Básico para a Sprint 1)
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Navegação
  go_router: ^13.2.0

  # Áudio (Usando apenas o Audioplayers para evitar conflito)
  audioplayers: ^5.2.1

  # Seleção de Arquivos (Para você baixar as músicas como usuário)
  file_picker: ^6.1.1
  permission_handler: ^11.3.1

  # Text-to-Speech (Para a IA ler as histórias)
  flutter_tts: ^3.8.5

  # Persistência local (Para salvar os pontos dos jogos e as histórias)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # UI/UX e Estilo
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Removi as pastas de assets que não existem no seu PC para o app não dar erro ao abrir
  assets:
    - assets/images/